# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
exclude: '.*\.(csv|tsv|xls)$'
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9019
    hooks:
    -   id: codemeta-description-updated
    -   id: use-tidy-description
    -   id: spell-check
        exclude: >
          (?x)^(
          .*\.[rR]|
          .*\.feather|
          .*\.jpeg|
          .*\.pdf|
          .*\.png|
          .*\.py|
          .*\.RData|
          .*\.rds|
          .*\.Rds|
          .*\.Rproj|
          .*\.sh|
          (.*/|)\.gitignore|
          (.*/|)\.gitlab-ci\.yml|
          (.*/|)\.lintr|
          (.*/|)\.pre-commit-.*|
          (.*/|)\.Rbuildignore|
          (.*/|)\.Renviron|
          (.*/|)\.Rprofile|
          (.*/|)\.travis\.yml|
          (.*/|)appveyor\.yml|
          (.*/|)NAMESPACE|
          (.*/|)renv/settings\.dcf|
          (.*/|)renv\.lock|
          (.*/|)WORDLIST|
          \.github/workflows/.*|
          data/.*|
          )$
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: no-debug-statement
    -   id: deps-in-desc
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: file-contents-sorter
        files: '^\.Rbuildignore$'
    -   id: end-of-file-fixer
        exclude: '\.Rd'
    -   id: check-json
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args:
        -   --fix=no
    -   id: trailing-whitespace
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
    -   args:
        -   build
        -   chore
        -   ci
        -   docs
        -   feat
        -   fix
        -   perf
        -   refactor
        -   revert
        -   style
        -   test
        -   bump
        id: conventional-pre-commit
        stages:
        -   commit-msg
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
    -   id: forbid-tabs
    -   id: remove-tabs
-   repo: local
    hooks:
    -   id: style_files
        name: Apply bioconductor style
        entry: >
            Rscript -e "styler::style_pkg(transformers = biocthis::bioc_style())"
        language: system
    -   id: lint_files
        name: Apply lintr
        entry: >
            Rscript -e "lintr::lint_package()"
        language: system
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.(Rhistory|RData|Rds|rds)$'
    -   id: codemeta-json-updated
        name: Update codemeta.json
        entry: >
          Rscript -e "codemetar::write_codemeta(force_update = FALSE)"
        language: system
        files: DESCRIPTION
        stages: [commit]
    -   id: bump-version
        name: Bump version
        entry: >
          ./utilities/bump-version.sh
        language: system
        always_run: true
        pass_filenames: false
        stages: [post-commit]
