on:
  push:
    branches:
      - devel
      - RELEASE*

name: Create Github Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag_version: ${{ steps.create_release.outputs.tag_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./utilities/create-github-release.sh

  create_release_artifacts:
    needs: [create-release]
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        r_version: ['release', 'devel']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Update system repositories
        run: sudo apt-get update
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libxml2-dev \
          libssl-dev libcurl4-openssl-dev \
          libharfbuzz-dev libfribidi-dev \
          pandoc
      - name: Setup R
        uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
        with:
          r-version: ${{ matrix.r_version }}
          use-public-rspm: true
        id: r
      - name: Install dependencies
        uses: r-lib/actions/setup-renv@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
      - name: Build Package
        run: R CMD build .
      - name: Rename Package
        run: echo "NEWNAME=$(./utilities/rename-package.R *.tar.gz)" >> "$GITHUB_ENV"
      - name: debug
        run: |
          echo "R version: ${{ steps.r.outputs.installed-r-version }}"
          echo "Current Tag: ${{ needs.create-release.outputs.tag_version }}"
          echo "Release File Name: ${{ env.NEWNAME }}"
      - name: Upload Release Artifact
        env:
          RELEASE_TAG: ${{ needs.create-release.outputs.tag_version }}
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ env.RELEASE_TAG }} ${{ env.NEWNAME }}
