name: Continuous Integration / R Workflows
on:
  push:
    branches:
    - master
    - main
    - RELEASE_**
  pull_request:
    branches:
    - master
    - main
    - RELEASE_**
jobs:
  rworkflows:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    strategy:
      fail-fast: ${{ false }}
      matrix:
        config:
        - os: ubuntu-latest
          bioc: devel
          r: auto
          cont: bioconductor/bioconductor_docker:devel
          rspm: https://packagemanager.rstudio.com/cran/__linux__/focal/release
        - os: macOS-latest
          bioc: release
          r: auto
        - os: windows-latest
          bioc: release
          r: auto
    steps:
    - if: ${{ env.ACT }}
      name: Hack container for local development
      run: |
        sudo apt-get update && sudo apt-get upgrade -y
        sudo apt-get install -y nodejs qpdf rsync build-essential
      shell: bash {0}
    - uses: neurogenomics/rworkflows@master
      with:
        run_bioccheck: ${{ true }}
        run_rcmdcheck: ${{ true }}
        as_cran: ${{ true }}
        run_vignettes: ${{ true }}
        has_testthat: ${{ true }}
        run_covr: ${{ true }}
        run_pkgdown: ${{ false }}
        has_runit: ${{ false }}
        has_latex: ${{ false }}
        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        run_docker: ${{ false }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        runner_os: ${{ runner.os }}
        cache_version: cache-v1
